Task 6. Design document
Gammanik/roguelike pull request #10
Opened 2020-09-09 15:22 UTC by Gammanik

В команде: Бобышев Никита, Александр Чернокоз

Добавили диздок: 
https://github.com/Gammanik/roguelike/blob/disdoc/src/main/kotlin/com/roguelike/docs/design_document.md

2020-09-09 19:19 UTC, yurii-litvinov requested changes
Надо ещё диаграмму последовательностей (которая sequence diagram) сюда впихнуть.

2020-09-09 19:19 UTC, yurii-litvinov commented on src/main/kotlin/com/roguelike/docs/design_document.md
> +### Архитектурное описание
Как-то всё наоборот. Начать следовало бы с общих сведений о системе --- что это игра, где цель игрока такая-то, геймплей такой-то и т.д. Затем --- architectural drivers, роли и случаи использования, и уже отталкиваясь от них --- детальная архитектура

2020-09-09 19:19 UTC, yurii-litvinov commented on src/main/kotlin/com/roguelike/docs/design_document.md
> +
Ограничения хорошо, хотя тот факт, что у персонального компьютера должны быть клавиатура и монитор, наверное, не стоит писать в технической документации уже лет 40 :) Никакое из этих соображений по сути архитектуру не определяет. А вот то, что игра реал-тайм --- да. Тайловая графика --- да. Однопользовательская --- возможно. И нефункциональные качества, которые вы считаете приоритетными, например, сопровождаемость или расширяемость

2020-09-09 19:19 UTC, yurii-litvinov commented on src/main/kotlin/com/roguelike/docs/design_document.md
> +создания объекта gamePanel, а также создает JFrame с компонентами infoMenuPanel и gamePanel.
Компоненты в архитектуре --- обычно что-то более абстрактное. Не файл main.kt, а, я не знаю, подсистема инициализации, не конкретное окно, а главное игровое поле или что-то такое. Ну и неплохо бы каждый компонент прокомментировать кратко, за что он отвечает, как вы тут начали.

2020-09-09 19:19 UTC, yurii-litvinov commented on src/main/kotlin/com/roguelike/docs/design_document.md
> +#### Диаграмма состояния моба и игры
Диаграмма про игру --- это скорее диаграмма активностей, что тоже хорошо, но не путайтесь в терминологии

2020-09-10 16:32 UTC, chernokoz commented on src/main/kotlin/com/roguelike/docs/design_document.md
> +### Архитектурное описание
Поправил последовательность.

2020-09-10 16:32 UTC, chernokoz commented on src/main/kotlin/com/roguelike/docs/design_document.md
> +
Поправил ограничения.

2020-09-10 16:34 UTC, chernokoz commented on src/main/kotlin/com/roguelike/docs/design_document.md
> +создания объекта gamePanel, а также создает JFrame с компонентами infoMenuPanel и gamePanel.
Поправил диаграмму, переписал комментарии к ним.

2020-09-10 16:39 UTC, Gammanik commented
Добавил диаграмму последовательностей.

2020-09-10 16:40 UTC, chernokoz commented on src/main/kotlin/com/roguelike/docs/design_document.md
> +#### Диаграмма состояния моба и игры
Поправил название.

2020-09-12 20:26 UTC, yurii-litvinov approved these changes
По-хорошему, для каждой роли пишут ещё портрет типичного пользователя, типа "Игрок Вася, 15 лет, нет друзей и жизни, сидит целыми днями за компьютером, умеет программировать, считает себя выше Call Of Duty, поэтому играет в игры С Глубоким Геймплеем". Иначе есть риск сделать систему, которая в принципе никому не нужна (типичный пример --- это бухгалтерское приложение, требующее скриптования на JavaScript --- авторы искренне уверены, что JS все знают).

Ещё на диаграмме последовательностей User рисуется как актор (человечек) с линией активации, совпадающей с линией жизни. Актор отличается от объекта тем, что способен "спонтанно" генерировать события, объект же имеет право только реагировать. Сейчас у вас выглядит так, будто User внезапно просыпается и вызыввает чей-то метод, что ок для актора, но не ок для обычного объекта.

И ещё я бы что-то сделал, чтобы связать диаграмму классов и компонентов --- например, писал бы на диаграмме классов полностью квалифицированные имена. Иначе непонятно, какой класс к какому компоненту относится.

Но в целом годно, так что не буду придираться, зачтена.

2020-09-14 12:23 UTC, closed without merging