Roguelike 1
Gammanik/roguelike pull request #4
Opened 2020-08-24 12:27 UTC by Gammanik

В команде: Александр Чернокоз, Бобышев Никита

В командах по 4 человека разработать первую версию Roguelike со следующими требованиями:

Консольная графика
Персонаж, перемещающийся по карте
Карта должна на выбор пользователя случайно генерироваться или грузиться из файла
Специальных требований на генератор карт не накладывается, но красивые результаты приветствуются
Оформить архитектурную документацию к текущей версии

Нельзя копипастить чужой код (смотреть в туториалы можно, заимствовать решения --- нет)

Обязательно указать при сдаче, с кем вы в команде

2020-08-24 13:37 UTC, yurii-litvinov requested changes
- Окошку выбора загрузки или генерации стоило бы прописать минимальный размер, а то его можно скукожить до неюзабельного состояния. Кстати, при размере по умолчанию у него несколько не помещается заголовок у меня, стоило бы увеличить
- В условии просили консольную графику :) Но ладно, это можно не править (хоть в реальной жизни за столь неприкрытое игнорирование ТЗ могут вкатить такую неустойку, что вы ещё будете должны заказчику).

А в целом ничего, только надо тесты, комментарии, и поправить замечания (из которых самое интересное, пожалуй, --- проверить, что на карте все области, которые должны быть достижимы, достижимы).

2020-08-24 13:37 UTC, yurii-litvinov commented on README.md
> +![rogue classes](./src/main/kotlin/docs/rogClasses.png)
Диаграмма вызывает некоторые вопросы, например, а кто владеет GamePanel и LoadMapMenu. Или с кем связаны классы Keys и Settings. Вообще, к началу работы над этой задачей уже должен был быть готов диздок, и тут ожидалась его сокращённая и подправленная версия, а поскольку вы делаете задачи не совсем в том порядке, архитектурное описание получилось не очень. Но ладно, давайте рогалик сделаете как умеете, а потом подготовите полноценный диздок по финальной версии, и закроет домашку про диздок.

2020-08-24 13:37 UTC, yurii-litvinov commented on src/main/kotlin/GamePanel.kt
> +class GamePanel(private val map : Map): JPanel(), KeyListener {
Традиционно хочется комментариев, к каждому классу (интерфейсу, перечислению и т.д. и т.п.) и каждому паблик-методу, кроме, быть может, override-ов, если у них у предка есть комментарий.

2020-08-24 13:37 UTC, yurii-litvinov commented on src/main/kotlin/GamePanel.kt
> +                        && !map.isWall(  person.xCoordinate+ 2,  person.yCoordinate + 1)) {
А тут перед `+` пробела не хватает :)

2020-08-24 13:37 UTC, yurii-litvinov commented on src/main/kotlin/graphics/LoadMapMenu.kt
> +    val fileChooser = JFileChooser()
Кажется, в Котлине видимость по умолчанию public, тогда делать поля без модификатора видимости --- плохая идея (тем более мутабельных типов). Нарушение инкапсуляции

2020-08-24 13:37 UTC, yurii-litvinov commented on src/main/kotlin/graphics/Map.kt
> +                }
Тут вы как-то совсем увлеклись пустыми строками. Обычно после `{` и перед `}` пустые строки не ставят, тем более что в остальном коде у вас не так, как тут

2020-08-24 13:37 UTC, yurii-litvinov commented on src/main/kotlin/graphics/model/BadMapFileException.kt
> +class BadMapFileException : Exception()
Кстати, даже исключениям нужен комментарий --- что означает, когда кидается

2020-08-24 13:37 UTC, yurii-litvinov commented on src/main/kotlin/graphics/model/MapPoint.kt
> +open class MapPoint(val x: Int, val y: Int, var col : Color)
И даже дата-классам :)

2020-08-24 13:37 UTC, yurii-litvinov commented on src/main/kotlin/main.kt
> +    while(!loadMapMenu.isMapLoaded) {
И тут пробела не хватает, перед `(`

2020-08-24 13:37 UTC, yurii-litvinov commented on src/test/kotlin/GameTest.kt
> +        assertEquals(2, 2)
Ну как-то не очень :)

2020-08-24 13:37 UTC, yurii-litvinov commented on src/main/kotlin/graphics/Map.kt
> +    }
А как-нибудь гарантируется, что карта связна? Тем более, что персонаж имеет размеры 2х2 клетки, было бы глупо его сгенерить в изолированном от остальной карты углу, заставленном стенами.

2020-08-24 19:26 UTC, chernokoz commented on src/main/kotlin/graphics/Map.kt
> +    }
Да, рандомизация карты заключается в выборе рандомного подмножества фиксированного размера из заданного множества, которое уже гарантирует связность по построению. Возможно образование лишь небольших комнаток, но персонаж не может быть заперт внутри них.

Также из мыслей к этому вопросу: в следующих частях задания Roguelike при необходимости можно сделать после генерации карты dfs для предподсчета множества достижимых клеток, после этого генерировать объекты(монетки, врагов) только в множестве достижимых клеток. Также можно добавить возможность разрушать стены ударом.

2020-08-24 19:27 UTC, chernokoz commented on src/main/kotlin/graphics/Map.kt
> +    }
Да, забыл добавить самое главное: dfs можно реализовать с учетом размера персонажа 2x2, это лишь дело техники.

2020-08-24 19:33 UTC, chernokoz commented
> * Окошку выбора загрузки или генерации стоило бы прописать минимальный размер, а то его можно скукожить до неюзабельного состояния. Кстати, при размере по умолчанию у него несколько не помещается заголовок у меня, стоило бы увеличить

Окна сделали неизменяемого размера. Окно загрузки или генерации увеличил, проверил на винде - теперь заголовок  помещается. Также этот Ваш вопрос заставил задуматься о кроссплатформенности, запускал на виндоусе и видел, что главная панель игры там полностью не влезала в окно, хотя на маке все было отлично. Решил проблему с помощью метода pack(), теперь окно всегда по размеру gamePanel. Проверил на windows и macOS.

2020-08-24 19:35 UTC, Gammanik commented on src/main/kotlin/graphics/LoadMapMenu.kt
> +    val fileChooser = JFileChooser()
Поправил

2020-08-24 19:35 UTC, Gammanik commented on src/main/kotlin/GamePanel.kt
> +                        && !map.isWall(  person.xCoordinate+ 2,  person.yCoordinate + 1)) {
Исправил

2020-08-24 19:37 UTC, Gammanik commented on src/main/kotlin/graphics/Map.kt
> +                }
Исправлено. Возможно, стоило бы добавить линтер к CI

2020-08-24 19:37 UTC, Gammanik commented on src/main/kotlin/graphics/model/BadMapFileException.kt
> +class BadMapFileException : Exception()
Исправил

2020-08-24 19:37 UTC, Gammanik commented on src/main/kotlin/main.kt
> +    while(!loadMapMenu.isMapLoaded) {
Исправил

2020-08-24 19:38 UTC, Gammanik commented on src/test/kotlin/GameTest.kt
> +        assertEquals(2, 2)
Добавил тесты на загрузку карты

2020-08-24 19:39 UTC, Gammanik commented on README.md
> +![rogue classes](./src/main/kotlin/docs/rogClasses.png)
Подправил немного диаграмму

2020-08-24 19:39 UTC, Gammanik commented on src/main/kotlin/GamePanel.kt
> +class GamePanel(private val map : Map): JPanel(), KeyListener {
Добавил комментарии

2020-08-25 16:51 UTC, yurii-litvinov commented
А уже можно смотреть? Если да, то лучше отметьте это на HwProj.

2020-08-25 16:53 UTC, chernokoz commented
> А уже можно смотреть? Если да, то лучше отметьте это на HwProj.

Да, уже можно, сейчас пометим

2020-08-25 17:24 UTC, yurii-litvinov commented on src/main/kotlin/graphics/Map.kt
> +    }
Принято. Это, кстати, как раз то, что стоит писать в диздоке --- хороший пример соображения, которое важно, но не очевидно из кода.

2020-08-25 17:44 UTC, yurii-litvinov requested changes
Уже почти, но надо ещё немного доисправлять

2020-08-25 17:44 UTC, yurii-litvinov commented on src/main/kotlin/graphics/GameMap.kt
> +    val rectMap = mutableMapOf<Pair<Int, Int>, MapPoint>()
А val-ы тоже по умолчанию public? Тогда это плохо, немутабельная ссылка, но на мутабельный объект, извне могут влезть и всё испортить

2020-08-25 17:44 UTC, yurii-litvinov commented on src/main/kotlin/graphics/GameMap.kt
> +package graphics
Кстати, ещё имена пакетов неканоничны. В Kotlin принята Java-схема, где префикс имени любого пакета --- это обратное доменное имя (желательно то, которым владет разработчик пакета), чтобы обеспечить глобальную уникальность. Например, com.example.graphics

2020-08-25 17:44 UTC, yurii-litvinov commented on src/main/kotlin/graphics/LoadMapMenu.kt
> +    var isMapLoaded = false
Паблик-поля нельзя :)

2020-08-25 17:44 UTC, yurii-litvinov commented on src/test/kotlin/GameTest.kt
> +}
Тестовое покрытие не впечатляет. Лучше, чем ничего, да, но я б проверял движения персонажа --- что он не ходит в стену, ходит в пустое пространство, не может вывалиться за уровень, например. Вообще, тестировать надо всё, что в принципе можно без эпических усилий протестировать (например, ввод пользователя и отрисовку UI теоретически возможно, но сложно, поэтому не надо тут --- а в реальной жизни такое тоже делают). Желательно достичь сколько-нибудь разумного тестового покрытия бизнес-логики.

2020-08-26 09:49 UTC, Gammanik commented on src/main/kotlin/graphics/GameMap.kt
> +    val rectMap = mutableMapOf<Pair<Int, Int>, MapPoint>()
По умолчанию plblic, да. Исправил. 
Сделал переменную private и метод, который возвращает иммутабельный мап

2020-08-26 09:55 UTC, Gammanik commented on src/main/kotlin/graphics/GameMap.kt
> +package graphics
Переместил в com.roguelike

2020-08-26 09:55 UTC, Gammanik commented on src/main/kotlin/graphics/LoadMapMenu.kt
> +    var isMapLoaded = false
сделал приватный сеттер

2020-08-26 10:00 UTC, Gammanik commented on src/test/kotlin/GameTest.kt
> +}
Добавил несколько тестов на движения. Мы уже начали реализовывать вторую часть и в ней выделен специальный класс `Checker`, который отвечает за проверку возможности движения. Его будет проще тестировать.

2020-08-26 10:34 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2020-08-29 10:46 UTC, closed without merging