Roguelike 3
Gammanik/roguelike pull request #9
Opened 2020-09-01 20:25 UTC by Gammanik

В команде: Никита Бобышев, Александр Чернокоз

2020-09-02 12:32 UTC, yurii-litvinov requested changes
- Тестовое покрытие не очень. Например, эффекты от вещей вообще не тестируются, команды не тестируются (и, кстати, ConfusionDecorator). Посмотрите Code Coverage в IDEA. Всякие методы, связанные с рисованием, можно и не тестировать, но бизнес-логика должна быть покрыта адекватно (хотя бы процентов 90 строк кода).
- Хочется ещё больше команд --- например, перемещение персонажа тоже могло бы быть командами реализовано.
- Хочется не только расходуемые предметы, по условию их должно быть можно надеть (и получить какой-то бонус) и снять
- Кстати, если попытаться использовать предмет, если в инвентаре ничего не выбрано, бросается исключение, но игра не падает

2020-09-02 12:32 UTC, yurii-litvinov commented on src/main/kotlin/com/roguelike/graphics/map_loading/LoadMapMenu.kt
> +                RandomMapCommand(gameMap).execute()
У вас роль команд играет AbstractAction, а команды вообще не нужны, потому что создаются только для того, чтобы тут же исполниться. Я бы этот кусок переписал так, чтобы AbstractAction-ы только диспетчеризовали запросы, пересылая их заранее зарегистрированным командам, которые бы уже эти запросы и исполняли. Например, любой контрол, который может реагировать на действия пользователя, реализует какой-нибудь интерфейс, в котором декларируется метод регистрации команды с соответствующей ей клавишей, тогда в main-е мы создаём контролы и команды, регистрируем команды в контролах, и дальше уже оно само. Или даже сделать отдельный контроллер, который будет просто дёргаться из контролов, а команды будут храниться в нём.

В любом случае, это позволит упорядочить взаимодействие с пользователем: у вас в коде будет ровно одно место, где команды создаются, им назначаются клавиши и они регистрируются. Сильно облегчает жизнь в приложениях с более развитым UI, где точек взаиммодействия с пользователем сотни.

2020-09-02 12:32 UTC, yurii-litvinov commented on src/main/kotlin/com/roguelike/commands/SaveGameCommand.kt
> +        val file = File("src/main/resources/snapshots", "snapshot")
Папки snapshots нету (гит не умеет хранить пустые папки, если  что), сама она не создаётся, так что сохранение не работает

2020-09-03 23:19 UTC, chernokoz commented on src/main/kotlin/com/roguelike/commands/SaveGameCommand.kt
> +        val file = File("src/main/resources/snapshots", "snapshot")
Сделал так, чтобы она создавалась в случае отсутствия, проблема решена!

2020-09-03 23:19 UTC, chernokoz commented on src/main/kotlin/com/roguelike/InfoMenuPanel.kt
> +                (790 * (v1.toDouble() / v2)).toInt(), 20,true)
Поправил!

2020-09-03 23:22 UTC, chernokoz commented
`Хочется не только расходуемые предметы, по условию их должно быть можно надеть (и получить какой-то бонус) и снять`
Сделано, добавил надеваемую броню

`Кстати, если попытаться использовать предмет, если в инвентаре ничего не выбрано, бросается исключение, но игра не падает`
Поправил, теперь есть дополнительный чек на то, что предмет с таким номером есть в рюкзаке

2020-09-03 23:25 UTC, Gammanik commented on src/main/kotlin/com/roguelike/graphics/map_loading/LoadMapMenu.kt
> +                RandomMapCommand(gameMap).execute()
Сделал `CommandController`, в котором можно регистрировать команды и в котором хранится `keyToCommand` мап. Перемещение персонажа сложно реализовать в виде команды, так как оно зависит от таймера и флагов вида `isKeyUp`, `isKeyDown` итд. Было реализовано так для того, чтобы можно было ходить по диагонали.

2020-09-04 00:00 UTC, Gammanik commented
Добавил еще несколько тестов на айтемы и на загрузку. Вроде, основная логика покрыта.

2020-09-04 09:40 UTC, yurii-litvinov approved these changes
Да, в целом теперь всё ок, зачтена. Ходить по дигонали --- это круто, да, в прошлый раз не заметил, что так можно. Ещё вторую шкалу с HP в EXP, наверное, стоило переименовать.

2020-09-04 09:40 UTC, yurii-litvinov commented on src/main/kotlin/com/roguelike/commands/CommandController.kt
> +class CommandController private constructor(){
Надо ещё комментарии по-хорошему

2020-09-04 09:40 UTC, yurii-litvinov commented on src/main/kotlin/com/roguelike/commands/CommandController.kt
> +        fun getInstance(): CommandController {
Я вот не люблю синглтоны --- они осложняют тестирование и приводят к переписыванию половины системы, если синглтон таки оказался не синглтоном

2020-09-04 09:40 UTC, yurii-litvinov commented on src/main/kotlin/com/roguelike/commands/CommandController.kt
> +        am?.put(key, object : AbstractAction() {
Сокращать идентификаторы ужасно

2020-09-04 09:56 UTC, Gammanik commented on src/main/kotlin/com/roguelike/commands/CommandController.kt
> +        fun getInstance(): CommandController {
и часто может выродиться в god object. Нужно было создавать его в main и добавлять в конструктор gamePanel

2020-09-04 09:57 UTC, Gammanik commented on src/main/kotlin/com/roguelike/commands/CommandController.kt
> +class CommandController private constructor(){
Добавил

2020-09-04 09:57 UTC, Gammanik commented on src/main/kotlin/com/roguelike/commands/CommandController.kt
> +        am?.put(key, object : AbstractAction() {
исправил

2020-09-04 09:57 UTC, Gammanik commented
Спасибо!

2020-09-04 09:57 UTC, merged